// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "what-time-is-it.proto" (package "whattimeisit", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WhatTimeIsItService } from "./what-time-is-it";
import type { WhatTimeIsItRightNowStreamResponse } from "./what-time-is-it";
import type { WhatTimeIsItRightNowStreamRequest } from "./what-time-is-it";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { WhatTimeIsItRightNowResponse } from "./what-time-is-it";
import type { WhatTimeIsItRightNowRequest } from "./what-time-is-it";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service whattimeisit.WhatTimeIsItService
 */
export interface IWhatTimeIsItServiceClient {
    /**
     * @generated from protobuf rpc: WhatTimeIsItRightNow(whattimeisit.WhatTimeIsItRightNowRequest) returns (whattimeisit.WhatTimeIsItRightNowResponse);
     */
    whatTimeIsItRightNow(input: WhatTimeIsItRightNowRequest, options?: RpcOptions): UnaryCall<WhatTimeIsItRightNowRequest, WhatTimeIsItRightNowResponse>;
    /**
     * @generated from protobuf rpc: WhatTimeIsItRightNowStream(whattimeisit.WhatTimeIsItRightNowStreamRequest) returns (stream whattimeisit.WhatTimeIsItRightNowStreamResponse);
     */
    whatTimeIsItRightNowStream(input: WhatTimeIsItRightNowStreamRequest, options?: RpcOptions): ServerStreamingCall<WhatTimeIsItRightNowStreamRequest, WhatTimeIsItRightNowStreamResponse>;
}
/**
 * @generated from protobuf service whattimeisit.WhatTimeIsItService
 */
export class WhatTimeIsItServiceClient implements IWhatTimeIsItServiceClient, ServiceInfo {
    typeName = WhatTimeIsItService.typeName;
    methods = WhatTimeIsItService.methods;
    options = WhatTimeIsItService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: WhatTimeIsItRightNow(whattimeisit.WhatTimeIsItRightNowRequest) returns (whattimeisit.WhatTimeIsItRightNowResponse);
     */
    whatTimeIsItRightNow(input: WhatTimeIsItRightNowRequest, options?: RpcOptions): UnaryCall<WhatTimeIsItRightNowRequest, WhatTimeIsItRightNowResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WhatTimeIsItRightNowRequest, WhatTimeIsItRightNowResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WhatTimeIsItRightNowStream(whattimeisit.WhatTimeIsItRightNowStreamRequest) returns (stream whattimeisit.WhatTimeIsItRightNowStreamResponse);
     */
    whatTimeIsItRightNowStream(input: WhatTimeIsItRightNowStreamRequest, options?: RpcOptions): ServerStreamingCall<WhatTimeIsItRightNowStreamRequest, WhatTimeIsItRightNowStreamResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WhatTimeIsItRightNowStreamRequest, WhatTimeIsItRightNowStreamResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
